name: mini_ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_crashlytics: ^5.0.1
  provider: ^6.1.5+1
  json_serializable: ^6.11.1
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.13.1
  google_sign_in: ^6.2.1
  flutter_stripe: ^12.0.2
  firebase_messaging: ^16.0.1
  http: ^1.1.0
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  permission_handler: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
